os: linux
dist: xenial
language: generic

addons:
  ssh_known_hosts: $BITWARDEN_HOST

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - echo -e "Host $BITWARDEN_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - envsubst < .env.template > .env
  - chmod +x deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
